name: 'checks'
on:
  pull_request:

jobs:
  ensure-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: danieljimeneznz/ensure-files-changed@v4.1.0
        with:
          require-changes-to: |
            CHANGELOG.md
          prevent-changes-to: |
            LICENSE.md
          token: ${{ secrets.GITHUB_TOKEN }}
